set nocompatible
set backspace=2
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'vim-airline/vim-airline'

call vundle#end()
filetype plugin indent on
set number
syntax on
set laststatus=2
colorscheme slate
"colorscheme solarized
"set background=dark